//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryDiscrepancy
    {
        public int DiscrepancyID { get; set; }
        public int ProductID { get; set; }
        public int ManagerQuantity { get; set; }
        public int SupplierQuantity { get; set; }
        public int DiscrepancyAmount { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
