//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Inventory = new HashSet<Inventory>();
        }
    
        public int ProductID { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal SellingPrice { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string StorageConditions { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> id_status_order { get; set; }
        public Nullable<int> id_warehouse { get; set; }
        public Nullable<int> id_reserv { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventory { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual reservation_status reservation_status { get; set; }
    }
}
